# -*- coding: utf-8 -*-
"""dashboard_kepuasan_lengkap.app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3_4lUPeCLs93CALfCLylqf1nhWpEhHJ
"""

import streamlit as app
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as stats
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# =====================================================
# SETUP DASHBOARD
# =====================================================
app.set_page_config(page_title="Analisis Kepuasan Pegawai", layout="wide")
app.title("📌 Dashboard Evaluasi Kepuasan Layanan")
app.caption("Visualisasi dan analisis data survei berbasis indikator")

# =====================================================
# IMPORT DATA
# =====================================================
data = pd.read_excel("/content/data_simulasi_50_siswa_20_soal_baru.xlsx")

# Ambil 5 indikator utama
variabel = data.iloc[:, 1:6]
variabel = variabel.apply(pd.to_numeric, errors="coerce")

# =====================================================
# HITUNG INDEKS KEPUASAN
# =====================================================
rata_indikator = variabel.mean()
nilai_ikm = (rata_indikator.mean() / 5) * 100

def klasifikasi(nilai):
    kategori = {
        (81,100): "Sangat Baik",
        (66,80): "Baik",
        (51,65): "Cukup",
        (0,50): "Kurang"
    }
    for batas, label in kategori.items():
        if batas[0] <= nilai <= batas[1]:
            return label

c1, c2, c3 = app.columns(3)
c1.metric("IKM (%)", f"{nilai_ikm:.2f}")
c2.metric("Kategori Mutu", klasifikasi(nilai_ikm))
c3.metric("Jumlah Responden", data.shape[0])

app.divider()

# =====================================================
# ANALISIS SELISIH (GAP)
# =====================================================
app.subheader("Analisis Selisih Kepuasan")

selisih = 5 - rata_indikator
indikator_prioritas = selisih.sort_values(ascending=False).index[0]

fig1, ax1 = plt.subplots()
ax1.bar(selisih.index, selisih.values)
ax1.set_title("Selisih Skor Tiap Indikator")
ax1.set_ylabel("Nilai Selisih")
ax1.tick_params(axis='x', rotation=45)

app.pyplot(fig1)
app.warning(f"Indikator prioritas peningkatan: *{indikator_prioritas}*")

app.divider()

# =====================================================
# ANALISIS HUBUNGAN (KORELASI)
# =====================================================
app.subheader("Analisis Hubungan Antar Variabel")

mat_korelasi = variabel.corr()

fig2, ax2 = plt.subplots()
heat = ax2.imshow(mat_korelasi, cmap="viridis")
plt.colorbar(heat)

ax2.set_xticks(range(len(mat_korelasi.columns)))
ax2.set_yticks(range(len(mat_korelasi.columns)))
ax2.set_xticklabels(mat_korelasi.columns, rotation=45)
ax2.set_yticklabels(mat_korelasi.columns)

app.pyplot(fig2)

ranking = mat_korelasi.iloc[:-1, -1].sort_values(ascending=False)
app.dataframe(ranking.to_frame("Korelasi terhadap Indikator Akhir"))

app.divider()

# =====================================================
# ANALISIS REGRESI
# =====================================================
app.subheader("Model Regresi Linear")

X = stats.add_constant(variabel.iloc[:, 0:4])
Y = variabel.iloc[:, 4]

regresi = stats.OLS(Y, X).fit()

koef = regresi.params[1:]
nilai_r2 = regresi.rsquared

fig3, ax3 = plt.subplots()
ax3.bar(koef.index, koef.values)
ax3.axhline(0)
ax3.set_title("Nilai Koefisien Regresi")

app.pyplot(fig3)
app.info(f"Koefisien Determinasi (R²): {nilai_r2:.3f}")
app.success(f"Variabel paling berpengaruh: {koef.abs().idxmax()}")

app.divider()

# =====================================================
# SEGMENTASI RESPONDEN (CLUSTERING)
# =====================================================
app.subheader("Segmentasi Kepuasan Pegawai")

normalisasi = StandardScaler()
data_scaled = normalisasi.fit_transform(variabel.fillna(variabel.mean()))

model_cluster = KMeans(n_clusters=3, random_state=10)
hasil_cluster = model_cluster.fit_predict(data_scaled)

df_cluster = variabel.copy()
df_cluster["Kelompok"] = hasil_cluster

rata_cluster = df_cluster.groupby("Kelompok").mean()

app.dataframe(rata_cluster)

app.success("Segmentasi selesai dilakukan.")